import { Role } from './types';

export const ROLES: Record<string, Role> = {
  // === HỘI PHƯỢNG HOÀNG (ORDER OF THE PHOENIX) — CRIMSON & GOLD ===
  HARRY_POTTER: {
    id: 'HARRY_POTTER',
    name: 'Harry Potter',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Kẻ Được Chọn · The Boy Who Lived',
    phaseType: 'PASSIVE',
    cardNumber: '№ 01/21',
    description: 'Trái tim của chiến dịch Bảy Potter và mục tiêu săn đuổi tối thượng của Voldemort.',
    ability: 'Bạn là mục tiêu săn lùng chính của Voldemort. Tuy nhiên, nếu bạn chết, Hội Phượng Hoàng vẫn có thể thắng nếu tiêu diệt được Voldemort, nhưng nhiệm vụ sẽ khó khăn hơn rất nhiều.',
    tacticalTip: 'Hãy ẩn mình trong đám đông, tận dụng các bản sao và đồng đội chắn đòn để tồn tại đến thời khắc quyết định.',
    flavorQuote: '“I don’t want anyone else to try to be a hero for me.”',
    badge: 'lightning',
    image: '/cards/harry.jpg'
  },
  RON_WEASLEY: {
    id: 'RON_WEASLEY',
    name: 'Ron Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Bạn Trung Thành · King Weasley',
    phaseType: 'PASSIVE',
    cardNumber: '№ 02/21',
    description: 'Dũng cảm, kiên định và sẵn sàng hy sinh thân mình vì tình bạn.',
    ability: 'Nếu Tử Thần Thực Tử (TTTT) tấn công Harry, Ron sẽ tự động chết thay cho Harry.',
    tacticalTip: 'Bạn là tấm khiên sinh mệnh tối thượng của Harry. Hãy quan sát và định hướng sự chú ý của phe ác về phía mình.',
    flavorQuote: '“Don’t let it worry you. It’s me, I’m extremely famous.”',
    badge: 'shield',
    image: '/cards/ron.jpg'
  },
  HERMIONE_GRANGER: {
    id: 'HERMIONE_GRANGER',
    name: 'Hermione Granger',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phù Thủy Uyên Bác · Brightest Witch',
    phaseType: 'NIGHT',
    cardNumber: '№ 03/21',
    description: 'Trí tuệ sắc bén, lập kế hoạch chi tiết cho cuộc trốn chạy định mệnh.',
    ability: 'Mỗi ban Đêm (Lượt TTTT hành động), có thể PM cho Merlin để hỏi danh tính thật của 1 người chơi (trừ Harry và Voldemort).',
    tacticalTip: 'Ưu tiên soi những người có phát ngôn bất thường hoặc dẫn dắt biểu quyết ban ngày.',
    flavorQuote: '“Fear of a name only increases fear of the thing itself.”',
    badge: 'book',
    image: '/cards/hermione.jpg'
  },
  ALBUS_DUMBLEDORE: {
    id: 'ALBUS_DUMBLEDORE',
    name: 'Albus Dumbledore',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Hiệu Trưởng Vĩ Đại · Supreme Mugwump',
    phaseType: 'NIGHT',
    cardNumber: '№ 04/21',
    description: 'Phù thủy vĩ đại nhất mọi thời đại, bảo hộ linh hồn Hogwarts.',
    ability: 'Mỗi ban Đêm, chọn 1 người để bảo vệ khỏi bị TTTT giết. Không được bảo vệ 1 người 2 lượt liên tiếp.',
    tacticalTip: 'Dự đoán mục tiêu bị nhắm bắn tiếp theo. Đừng bảo vệ bản thân quá nhiều nếu đồng đội then chốt đang gặp nguy.',
    flavorQuote: '“Words are, in my not-so-humble opinion, our most inexhaustible source of magic.”',
    badge: 'phoenix',
    image: '/cards/dumbledore.jpg'
  },
  SEVERUS_SNAPE: {
    id: 'SEVERUS_SNAPE',
    name: 'Severus Snape',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Bậc Thầy Bế Quan Bí Thuật · Điệp Viên Hai Mang',
    phaseType: 'NIGHT',
    cardNumber: '№ 05/21',
    description: 'Bậc thầy Độc Dược và Bế Quan Bí Thuật, người điệp viên cô độc mang gánh nặng sinh tử của Hội Phượng Hoàng.',
    ability: 'Mỗi đêm, Snape có thể niệm Sectumsempra bọc lót cho 1 người chơi: Nếu người đó bị Tử Thần Thực Tử tấn công, bùa chém của Snape sẽ rạch nát đòn ám sát, cứu sống mục tiêu! Nhưng nếu người đó KHÔNG bị tấn công, bùa lạc sẽ cắt đứt tai / làm bị thương khiến mục tiêu bị phong ấn kỹ năng ở vòng kế tiếp. Ngoài ra, nhờ Bế Quan Bí Thuật, Snape hoàn toàn miễn nhiễm trước các bùa soi danh tính.',
    tacticalTip: 'Hãy phán đoán mục tiêu hiểm yếu mà phe Ác sắp ám sát để bọc lót cứu mạng! Tránh niệm bùa bừa bãi vào đồng đội vô tội nếu không muốn họ bị trúng bùa lạc mất tai và tê liệt kỹ năng!',
    flavorQuote: '“After all this time? Always.”',
    badge: 'potion',
    image: '/cards/snape.jpg'
  },
  REMUS_LUPIN: {
    id: 'REMUS_LUPIN',
    name: 'Remus Lupin',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Sói Hào Hiệp · Moony',
    phaseType: 'NIGHT',
    cardNumber: '№ 06/21',
    description: 'Chiến binh quả cảm của Hội, chuyên gia phòng chống nghệ thuật Hắc Ám.',
    ability: 'Có 1 lọ thuốc hồi sinh. Trong suốt ván chơi, có thể hồi sinh 1 người vừa bị giết ban đêm.',
    tacticalTip: 'Giữ bình thuốc cho các nhân vật chủ chốt như Harry, Dumbledore hoặc Hermione.',
    flavorQuote: '“It is the quality of one’s convictions that determines success, not the number of followers.”',
    badge: 'moon',
    image: '/cards/lupin.jpg'
  },
  ALASTOR_MOODY: {
    id: 'ALASTOR_MOODY',
    name: 'Alastor "Mắt Điên" Moody',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Thần Sáng Khét Tiếng · Constant Vigilance',
    phaseType: 'DAY',
    cardNumber: '№ 07/21',
    description: 'Chỉ huy chiến thuật của chiến dịch Bảy Potter, cảnh giác cao độ không khoan nhượng.',
    ability: 'Có 1 phát súng (Avada). Ban Ngày (Lúc Vote), có thể lập tức bắn chết 1 người. Nếu bắn nhầm HPH, Moody sẽ tự chết.',
    tacticalTip: 'Chỉ bóp cò khi bạn có bằng chứng chắc chắn trên 90% kẻ đó là Tử Thần Thực Tử.',
    flavorQuote: '“Constant vigilance! Never let your guard down!”',
    badge: 'wand',
    image: '/cards/moody.jpg'
  },
  RUBEUS_HAGRID: {
    id: 'RUBEUS_HAGRID',
    name: 'Rubeus Hagrid',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Lai Khổng Lồ · Keeper of Keys',
    phaseType: 'PASSIVE',
    cardNumber: '№ 08/21',
    description: 'Người lái chiếc mô tô bay đưa Harry xuyên qua làn mưa bùa chú tử thần.',
    ability: 'Sức khỏe phi thường, phải bị TTTT tấn công 2 lần mới chết. (Lần 1 đánh hụt/chỉ làm bị thương).',
    tacticalTip: 'Bạn có thể tự tin phát biểu và khiêu khích phe ác dồn sát thương vào bạn.',
    flavorQuote: '“What’s comin’ will come, an’ we’ll meet it when it does.”',
    badge: 'shield',
    image: '/cards/hagrid.jpg'
  },
  ARTHUR_WEASLEY: {
    id: 'ARTHUR_WEASLEY',
    name: 'Arthur Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Trụ Cột Nhà Weasley · Ministry Veteran',
    phaseType: 'NIGHT',
    cardNumber: '№ 09/21',
    description: 'Người cha tận tụy của gia đình Weasley, luôn theo dõi hoạt động của thế lực Hắc Ám tại Bộ.',
    ability: 'Mỗi đêm, có thể chọn 1 người chơi để xem phe của họ (HPH hay TTTT). Ngoài ra, 1 lần trong game vào ban ngày, có thể yêu cầu HPH biết tất cả kẻ thù của mình.',
    tacticalTip: 'Dùng khả năng xem phe vào ban đêm để soi những người đáng nghi. Dành Ultimate cho thời điểm then chốt khi cần xác nhận 4T.',
    flavorQuote: '“Never trust anything that can think for itself if you can’t see where it keeps its brain.”',
    badge: 'phoenix',
    image: '/cards/arthur.jpg'
  },
  FRED_WEASLEY: {
    id: 'FRED_WEASLEY',
    name: 'Fred Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Anh Em Sinh Đôi · Weasley Twin',
    phaseType: 'SPECIAL',
    cardNumber: '№ 10/21',
    description: 'Hài hước, táo bạo và không hề nao núng trước thế lực bóng tối. Đồng sáng lập tiệm Phù Thủy Quỷ Quái.',
    ability: 'Mỗi đêm, có thể tạo 1 Kẹo Ngất Xỉu và đưa cho 1 người chơi. Người đó sẽ bị mất quyền vote ở vòng phán quyết tiếp theo. (Item đặc biệt: nằm ngoài giới hạn item thường của game)',
    tacticalTip: 'Dùng Kẹo Ngất Xỉu để làm cứng hành động của những người đáng nghi nhất. Kết hợp với George để tạo combo confuse cực mạnh!',
    flavorQuote: '“Mischief managed! We solemnly swear that we are up to no good.”',
    badge: 'potion',
    image: '/cards/fred.jpg'
  },
  GEORGE_WEASLEY: {
    id: 'GEORGE_WEASLEY',
    name: 'George Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Anh Em Sinh Đôi · Saint-like',
    phaseType: 'SPECIAL',
    cardNumber: '№ 11/21',
    description: 'Dù mất đi một bên tai trong trận không chiến, lòng dũng cảm vẫn vẹn nguyên. Đồng sáng lập tiệm Phù Thủy Quỷ Quái.',
    ability: 'Mỗi đêm, có thể tạo 1 Bột Khói Mù Peru và rải lên bầu trời. Toàn bộ TTTT bị SULK (mất quyền ám sát) trong đêm đó. (Item đặc biệt: nằm ngoài giới hạn item thường của game)',
    tacticalTip: 'Chờ thời điểm then chốt khi Dumbledore bảo vệ Harry hoặc khi cần bảo vệ 1 đêm. Kết hợp với Fred để tạo combo confuse + protect!',
    flavorQuote: '“You see, I\'m holy, Fred. Geddit? Saint-like.”',
    badge: 'potion',
    image: '/cards/george.jpg'
  },
  MUNDUNGUS_FLETCHER: {
    id: 'MUNDUNGUS_FLETCHER',
    name: 'Mundungus Fletcher',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Kẻ Hèn Nhát · Scoundrel of the Order',
    phaseType: 'SPECIAL',
    cardNumber: '№ 12/21',
    description: 'Tay buôn lậu chợ đen, luôn tìm cách luồn lách bảo toàn mạng sống.',
    ability: 'Khi bị TTTT giết, có thể chọn 1 người bất kỳ chết thay mình (1 lần duy nhất trong tình trạng khẩn cấp).',
    tacticalTip: 'Nếu bị tấn công, hãy nhắm vào kẻ bạn nghi ngờ nhất là phe đối phương để đổi mạng.',
    flavorQuote: '“I never volunteered for this! There was hundreds of ’em!”',
    badge: 'mask',
    image: '/cards/mundungus.jpg'
  },
  KINGSLEY_SHACKLEBOLT: {
    id: 'KINGSLEY_SHACKLEBOLT',
    name: 'Kingsley Shacklebolt',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Thần Sáng Hoàng Gia · Auror Commander',
    phaseType: 'NIGHT',
    cardNumber: '№ 13/21',
    description: 'Thần Sáng điềm tĩnh, chỉ huy đội cận vệ và là niềm hy vọng của Bộ.',
    ability: 'Nếu có 1 HPH bị TTTT giết ban đêm, Kingsley sẽ CỨU SỐNG người đó (100% thay vì 50%). Ngoài ra, Kingsley miễn nhiễm khỏi bùa Silencing.',
    tacticalTip: 'Kích hoạt thế trận ứng cứu mỗi khi cảm nhận phe ác sắp ra đòn nhắm vào nhân vật mấu chốt. Với miễn nhiễm Silencing, Kingsley luôn có thể hành động!',
    flavorQuote: '”The Ministry has fallen. Scrimgeour is dead. They are coming.”',
    badge: 'shield',
    image: '/cards/kingsley.jpg'
  },
  BILL_WEASLEY: {
    id: 'BILL_WEASLEY',
    name: 'Bill Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phá Bùa Cổ Xưa · Curse Breaker',
    phaseType: 'NIGHT',
    cardNumber: '№ 14/21',
    description: 'Chuyên gia phá bùa Gringotts, cưỡi Thestral chiến đấu bên cạnh người bạn đời. Kinh nghiệm chiến đấu với bùa chú lờ nguy hiểm.',
    ability: 'Mỗi đêm, có thể chọn 1 người bị phong ấn (bị silence bởi bùa khác) để giải phong ấn cho họ. Ngoài ra, khi Bill chết, tất cả HPH được biết 1 người TTTT ngẫu nhiên.',
    tacticalTip: 'Ưu tiên giải phong ấn cho Dumbledore, Snape hoặc Hermione. Khi Bill hy sinh, hãy hy sinh anh dũng để lộ kẻ thù!',
    flavorQuote: '”It would take more than a werewolf to stop Fleur loving me.”',
    badge: 'ring',
    image: '/cards/bill.jpg'
  },
  FLEUR_DELACOUR: {
    id: 'FLEUR_DELACOUR',
    name: 'Fleur Delacour',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Tình Yêu Veela · Beauxbatons Champion',
    phaseType: 'NIGHT',
    cardNumber: '№ 15/21',
    description: 'Nữ quán quân tài hoa từ Beauxbatons, vẻ đẹp kiêu kỳ gắn liền với sự thủy chung sắt son. Lưỡi kiếm bạc của mình là vũ khí lợi hại.',
    ability: 'Mỗi đêm, có thể dùng Lưỡi Kiếm Gryffindor để chặt 1 người chơi. Người đó sẽ bị LOẠI KHỎI TRÒ CHƠI NGAY LẬP TỨC (không qua vote, không có death log giấu role). Tuy nhiên, nếu chặt nhầm người vô tội, Fleur phải tự chết.',
    tacticalTip: 'Chỉ dùng khi chắc chắn 90%+ người đó là 4T. Combo với Bill để xác nhận mục tiêu trước khi chặt!',
    flavorQuote: '”I am good-looking enough for both of us, I theenk!”',
    badge: 'ring',
    image: '/cards/fleur.jpg'
  },
  NYMPHADORA_TONKS: {
    id: 'NYMPHADORA_TONKS',
    name: 'Nymphadora Tonks',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phù Thủy Biến Hình · Metamorphmagus',
    phaseType: 'SPECIAL',
    cardNumber: '№ 16/21',
    description: 'Khả năng thay đổi dung mạo tùy ý, luôn mang lại bất ngờ cho chiến trường.',
    ability: 'Khi chết, có thể chọn biến thành 1 người khác (Kế thừa vai trò và năng lực của người đó).',
    tacticalTip: 'Khi ngã xuống, hãy kế thừa vai trò của người nắm giữ kỹ năng mạnh nhất đã chết.',
    flavorQuote: '“Don’t call me Nymphadora, Remus. It’s Tonks.”',
    badge: 'mask',
    image: '/cards/tonks.jpg'
  },
  POTTER_FAKE: {
    id: 'POTTER_FAKE',
    name: 'Bản Sao Harry',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Bảo Vệ · Polyjuice Decoy',
    phaseType: 'SPECIAL',
    cardNumber: '№ 17/21',
    description: 'Uống thuốc Đa Quả Dịch mang khuôn mặt Harry để đánh lừa Chúa Tể Hắc Ám.',
    ability: 'Chỉ có quyền vote vào Ban Ngày. 1 lần trong game, có thể tự reveal là Potter Fake và làm 1 người TTTT có vote cao nhất bị SILENCED ở vòng tiếp theo.',
    tacticalTip: 'Đóng giả là Harry thật trong các cuộc tranh luận để dụ dỗ kẻ thù. Dùng SILENCED khi đã xác định được mục tiêu!',
    flavorQuote: '”We are all Harry tonight.”',
    badge: 'potion',
    image: '/cards/potter_fake.jpg'
  },

  // === TỬ THẦN THỰC TỬ (DEATH EATERS) — EMERALD & SILVER ===
  VOLDEMORT: {
    id: 'VOLDEMORT',
    name: 'Chúa Tể Voldemort',
    faction: 'DEATH_EATERS',
    title: 'Chúa Tể Hắc Ám · He-Who-Must-Not-Be-Named',
    phaseType: 'NIGHT',
    cardNumber: '№ 18/21',
    description: 'Kẻ thống trị nghệ thuật Hắc Ám, dẫn đầu cuộc truy kích bầu trời với bùa phép chết chóc.',
    ability: 'Biết mặt toàn bộ TTTT. Quyết định ám sát ban đêm. Nếu bị giết, Tử Thần Thực Tử thua ngay lập tức.',
    tacticalTip: 'Giữ kín thân phận tuyệt đối. Để Bellatrix và Malfoy làm bia đỡ đạn cho bạn trong các cuộc bỏ phiếu.',
    flavorQuote: '“There is no good and evil, there is only power, and those too weak to seek it.”',
    badge: 'dark_mark',
    image: '/cards/voldemort.jpg'
  },
  BELLATRIX_LESTRANGE: {
    id: 'BELLATRIX_LESTRANGE',
    name: 'Bellatrix Lestrange',
    faction: 'DEATH_EATERS',
    title: 'Nữ Tử Thần Cuồng Tín · Dark Lieutenant',
    phaseType: 'PASSIVE',
    cardNumber: '№ 19/21',
    description: 'Tay sai trung thành cuồng tín nhất, tàn bạo và sẵn sàng tử vì đạo vì Chúa Tể.',
    ability: 'Nếu Bellatrix bị treo cổ ban ngày, ban đêm tiếp theo, Voldemort được quyền giết 2 người (Cơn thịnh nộ báo thù).',
    tacticalTip: 'Bạn là bẫy tử thần! Nếu bị dồn vào đường cùng, hãy để bị treo cổ để Voldemort quét sạch đối thủ.',
    flavorQuote: '“I killed Sirius Black! You coming to get me?”',
    badge: 'dagger',
    image: '/cards/bellatrix.jpg'
  },
  LUCIUS_MALFOY: {
    id: 'LUCIUS_MALFOY',
    name: 'Lucius Malfoy',
    faction: 'DEATH_EATERS',
    title: 'Quý Tộc Xảo Quyệt · Pureblood Patrician',
    phaseType: 'NIGHT',
    cardNumber: '№ 20/21',
    description: 'Ngoại giao giảo hoạt, luôn toan tính để gia tộc Malfoy sống sót.',
    ability: 'Mỗi đêm, có thể chọn 1 người để xem vai trò của họ. Ngoài ra, nếu bị treo cổ ban ngày, Voldemort sẽ bị KHÓA (không được ám sát) ở đêm tiếp theo.',
    tacticalTip: 'Dùng khả năng soi để tìm ra ai là HPH then chốt. Khi bị treo, hãy tự hào vì đã làm Voldemort an toàn!',
    flavorQuote: '”Let us hope Mr. Potter will always be around to save the day.”',
    badge: 'snake',
    image: '/cards/lucius.jpg'
  },
  PETER_PETTIGREW: {
    id: 'PETER_PETTIGREW',
    name: 'Peter Pettigrew',
    faction: 'DEATH_EATERS',
    title: 'Kẻ Phản Bội · Đuôi Trùn (Wormtail)',
    phaseType: 'NIGHT',
    cardNumber: '№ 21/21',
    description: 'Kẻ phản bội hèn hạ hóa thú thành chuột Scabbers, bầy tôi nợ mạng Harry Potter nhưng mang Bàn Tay Bạc của Chúa Tể Hắc Ám.',
    ability: 'Mỗi đêm trước khi giết, Pettigrew có thể chọn 1 người phe HPH để Đánh Hơi: Nhờ 12 năm sống ở Nhà Hang Sóc, nếu soi trúng Ron Weasley hoặc Harry Potter thật, hắn sẽ nhận diện ĐÍCH DANH người đó! Nếu trúng người khác, hắn biết họ là Đặc Biệt hay Bản Sao. Tuy nhiên, do mang Món Nợ Mạng (Life Debt) với Harry, Pettigrew KHÔNG THỂ trực tiếp bỏ phiếu ám sát Harry Potter thật. Ngoài ra, lần đầu tiên bị trục xuất ban ngày, hắn sẽ tự cắt ngón tay hóa chuột đào tẩu thoát chết!',
    tacticalTip: 'Hãy dùng khứu giác loài chuột để đánh hơi tìm ra đích danh Ron hoặc Harry Potter thật cho Voldemort. Nhưng nhớ rằng: bàn tay bạc của bạn sẽ bị tê liệt trước Harry do Món Nợ Máu, hãy để Voldemort hoặc đồng minh kết liễu Harry!',
    flavorQuote: '“You owe me, Wormtail! Your life belongs to me!”',
    badge: 'rat',
    image: '/cards/pettigrew.jpg'
  },
  FENRIR_GREYBACK: {
    id: 'FENRIR_GREYBACK',
    name: 'Fenrir Greyback',
    faction: 'DEATH_EATERS',
    title: 'Ma Sói Đồ Tể · Lycanthrope Savage',
    phaseType: 'NIGHT',
    cardNumber: '№ 22/21',
    description: 'Hung thần của bóng đêm, thích cắn xé và biến đổi phù thủy thành sinh vật lang thang.',
    ability: 'Một lần trong game vào ban đêm, có thể cắn 1 người. Người đó bị CHUYỂN SANG PHE TỬ THẦN THỰC TỬ (giữ nguyên kỹ năng cũ). Ngoài ra, Fenrir có thể cắn thêm 1 lần nữa vào cuối game để tăng sức mạnh 4T.',
    tacticalTip: 'Cắn những người có kỹ năng mạnh như Dumbledore, Hermione, hoặc Kingsley để cướp kỹ năng cho phe 4T!',
    flavorQuote: '“I like to bite \'em young... makes \'em easier to train.”',
    badge: 'wolf',
    image: '/cards/greyback.jpg'
  }
};
