import { Role } from './types';

export const ROLES: Record<string, Role> = {
  // === HỘI PHƯỢNG HOÀNG (ORDER OF THE PHOENIX) — CRIMSON & GOLD ===
  HARRY_POTTER: {
    id: 'HARRY_POTTER',
    name: 'Harry Potter',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Kẻ Được Chọn · The Boy Who Lived',
    phaseType: 'PASSIVE',
    cardNumber: '№ 01/21',
    description: 'Trái tim của chiến dịch Bảy Potter và mục tiêu săn đuổi tối thượng của Voldemort.',
    ability: 'Bạn là mục tiêu săn lùng chính của Voldemort. Tuy nhiên, nếu bạn chết, Hội Phượng Hoàng vẫn có thể thắng nếu tiêu diệt được Voldemort, nhưng nhiệm vụ sẽ khó khăn hơn rất nhiều.',
    tacticalTip: 'Hãy ẩn mình trong đám đông, tận dụng các bản sao và đồng đội chắn đòn để tồn tại đến thời khắc quyết định.',
    flavorQuote: '“I don’t want anyone else to try to be a hero for me.”',
    badge: 'lightning',
    image: '/cards/harry.jpg'
  },
  RON_WEASLEY: {
    id: 'RON_WEASLEY',
    name: 'Ron Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Bạn Trung Thành · King Weasley',
    phaseType: 'PASSIVE',
    cardNumber: '№ 02/21',
    description: 'Dũng cảm, kiên định và sẵn sàng hy sinh thân mình vì tình bạn.',
    ability: 'Nếu Tử Thần Thực Tử (TTTT) tấn công Harry, Ron sẽ tự động chết thay cho Harry.',
    tacticalTip: 'Bạn là tấm khiên sinh mệnh tối thượng của Harry. Hãy quan sát và định hướng sự chú ý của phe ác về phía mình.',
    flavorQuote: '“Don’t let it worry you. It’s me, I’m extremely famous.”',
    badge: 'shield',
    image: '/cards/ron.jpg'
  },
  HERMIONE_GRANGER: {
    id: 'HERMIONE_GRANGER',
    name: 'Hermione Granger',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phù Thủy Uyên Bác · Brightest Witch',
    phaseType: 'DAY',
    cardNumber: '№ 03/21',
    description: 'Trí tuệ sắc bén, lập kế hoạch chi tiết cho cuộc trốn chạy định mệnh.',
    ability: 'Mỗi ban Ngày (Lượt TTTT hành động), có thể PM cho GM để hỏi danh tính thật của 1 người chơi (trừ Harry và Voldemort).',
    tacticalTip: 'Ưu tiên soi những người có phát ngôn bất thường hoặc dẫn dắt biểu quyết ban đêm.',
    flavorQuote: '“Fear of a name only increases fear of the thing itself.”',
    badge: 'book',
    image: '/cards/hermione.jpg'
  },
  ALBUS_DUMBLEDORE: {
    id: 'ALBUS_DUMBLEDORE',
    name: 'Albus Dumbledore',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Hiệu Trưởng Vĩ Đại · Supreme Mugwump',
    phaseType: 'DAY',
    cardNumber: '№ 04/21',
    description: 'Phù thủy vĩ đại nhất mọi thời đại, bảo hộ linh hồn Hogwarts.',
    ability: 'Mỗi ban Ngày, chọn 1 người để bảo vệ khỏi bị TTTT giết. Không được bảo vệ 1 người 2 lượt liên tiếp.',
    tacticalTip: 'Dự đoán mục tiêu bị nhắm bắn tiếp theo. Đừng bảo vệ bản thân quá nhiều nếu đồng đội then chốt đang gặp nguy.',
    flavorQuote: '“Words are, in my not-so-humble opinion, our most inexhaustible source of magic.”',
    badge: 'phoenix',
    image: '/cards/dumbledore.jpg'
  },
  SEVERUS_SNAPE: {
    id: 'SEVERUS_SNAPE',
    name: 'Severus Snape',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Gián Điệp Nhị Trùng · Half-Blood Prince',
    phaseType: 'PASSIVE',
    cardNumber: '№ 05/21',
    description: 'Ẩn mình trong bóng tối, mang nỗi đau và lòng trung thành tuyệt đối.',
    ability: 'Bạn thuộc Hội Phượng Hoàng nhưng nếu Hermione soi bạn, GM sẽ báo bạn là Tử Thần Thực Tử. Nếu Pettigrew soi bạn, GM sẽ báo bạn là HPH.',
    tacticalTip: 'Cẩn trọng với những lời cáo buộc. Hermione có thể hiểu nhầm bạn, hãy chuẩn bị lý lẽ thuyết phục trong đêm treo cổ.',
    flavorQuote: '“After all this time? Always.”',
    badge: 'potion',
    image: '/cards/snape.jpg'
  },
  REMUS_LUPIN: {
    id: 'REMUS_LUPIN',
    name: 'Remus Lupin',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Sói Hào Hiệp · Moony',
    phaseType: 'DAY',
    cardNumber: '№ 06/21',
    description: 'Chiến binh quả cảm của Hội, chuyên gia phòng chống nghệ thuật Hắc Ám.',
    ability: 'Có 1 lọ thuốc hồi sinh. Trong suốt ván chơi, có thể hồi sinh 1 người vừa bị giết ban ngày.',
    tacticalTip: 'Giữ bình thuốc cho các nhân vật chủ chốt như Harry, Dumbledore hoặc Hermione.',
    flavorQuote: '“It is the quality of one’s convictions that determines success, not the number of followers.”',
    badge: 'moon',
    image: '/cards/lupin.jpg'
  },
  ALASTOR_MOODY: {
    id: 'ALASTOR_MOODY',
    name: 'Alastor "Mắt Điên" Moody',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Thần Sáng Khét Tiếng · Constant Vigilance',
    phaseType: 'NIGHT',
    cardNumber: '№ 07/21',
    description: 'Chỉ huy chiến thuật của chiến dịch Bảy Potter, cảnh giác cao độ không khoan nhượng.',
    ability: 'Có 1 phát súng (Avada). Ban Đêm (Lúc Vote), có thể lập tức bắn chết 1 người. Nếu bắn nhầm HPH, Moody sẽ tự chết.',
    tacticalTip: 'Chỉ bóp cò khi bạn có bằng chứng chắc chắn trên 90% kẻ đó là Tử Thần Thực Tử.',
    flavorQuote: '“Constant vigilance! Never let your guard down!”',
    badge: 'wand',
    image: '/cards/moody.jpg'
  },
  RUBEUS_HAGRID: {
    id: 'RUBEUS_HAGRID',
    name: 'Rubeus Hagrid',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Lai Khổng Lồ · Keeper of Keys',
    phaseType: 'PASSIVE',
    cardNumber: '№ 08/21',
    description: 'Người lái chiếc mô tô bay đưa Harry xuyên qua làn mưa bùa chú tử thần.',
    ability: 'Sức khỏe phi thường, phải bị TTTT tấn công 2 lần mới chết. (Lần 1 đánh hụt/chỉ làm bị thương).',
    tacticalTip: 'Bạn có thể tự tin phát biểu và khiêu khích phe ác dồn sát thương vào bạn.',
    flavorQuote: '“What’s comin’ will come, an’ we’ll meet it when it does.”',
    badge: 'shield',
    image: '/cards/hagrid.jpg'
  },
  ARTHUR_WEASLEY: {
    id: 'ARTHUR_WEASLEY',
    name: 'Arthur Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Trụ Cột Nhà Weasley · Ministry Veteran',
    phaseType: 'PASSIVE',
    cardNumber: '№ 09/21',
    description: 'Người cha tận tụy, chiến đấu bảo vệ gia đình và công lý phù thủy.',
    ability: 'Nếu 1 trong 3 cha con (Arthur, Fred, George) bị giết, 2 người kia sẽ chết theo (Hiệu ứng Domino Weasley).',
    tacticalTip: 'Liên kết bảo vệ nhau là sống còn. Hãy yêu cầu Dumbledore ưu tiên bọc lót nếu lộ diện.',
    flavorQuote: '“Never trust anything that can think for itself if you can’t see where it keeps its brain.”',
    badge: 'phoenix',
    image: '/cards/arthur.jpg'
  },
  FRED_WEASLEY: {
    id: 'FRED_WEASLEY',
    name: 'Fred Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Anh Em Sinh Đôi · Weasley Twin',
    phaseType: 'PASSIVE',
    cardNumber: '№ 10/21',
    description: 'Hài hước, táo bạo và không hề nao núng trước thế lực bóng tối.',
    ability: 'Nếu 1 trong 3 cha con (Arthur, Fred, George) bị giết, 2 người kia sẽ chết theo (Hiệu ứng Domino Weasley).',
    tacticalTip: 'Đánh lạc hướng Tử Thần Thực Tử bằng sự hoạt náo nhưng đừng để rơi vào tầm ngắm.',
    flavorQuote: '“Mischief managed! We solemnly swear that we are up to no good.”',
    badge: 'potion',
    image: '/cards/fred.jpg'
  },
  GEORGE_WEASLEY: {
    id: 'GEORGE_WEASLEY',
    name: 'George Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Anh Em Sinh Đôi · Saint-like',
    phaseType: 'PASSIVE',
    cardNumber: '№ 11/21',
    description: 'Dù mất đi một bên tai trong trận không chiến, lòng dũng cảm vẫn vẹn nguyên.',
    ability: 'Nếu 1 trong 3 cha con (Arthur, Fred, George) bị giết, 2 người kia sẽ chết theo (Hiệu ứng Domino Weasley).',
    tacticalTip: 'Giữ kín danh tính gia tộc Weasley để tránh thảm họa dây chuyền.',
    flavorQuote: '“You see, I’m holy, Fred. Geddit? Saint-like.”',
    badge: 'potion',
    image: '/cards/george.jpg'
  },
  MUNDUNGUS_FLETCHER: {
    id: 'MUNDUNGUS_FLETCHER',
    name: 'Mundungus Fletcher',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Kẻ Hèn Nhát · Scoundrel of the Order',
    phaseType: 'SPECIAL',
    cardNumber: '№ 12/21',
    description: 'Tay buôn lậu chợ đen, luôn tìm cách luồn lách bảo toàn mạng sống.',
    ability: 'Khi bị TTTT giết, có thể chọn 1 người bất kỳ chết thay mình (1 lần duy nhất trong tình trạng khẩn cấp).',
    tacticalTip: 'Nếu bị tấn công, hãy nhắm vào kẻ bạn nghi ngờ nhất là phe đối phương để đổi mạng.',
    flavorQuote: '“I never volunteered for this! There was hundreds of ’em!”',
    badge: 'mask',
    image: '/cards/mundungus.jpg'
  },
  KINGSLEY_SHACKLEBOLT: {
    id: 'KINGSLEY_SHACKLEBOLT',
    name: 'Kingsley Shacklebolt',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Thần Sáng Hoàng Gia · Auror Commander',
    phaseType: 'DAY',
    cardNumber: '№ 13/21',
    description: 'Thần Sáng điềm tĩnh, chỉ huy đội cận vệ và là niềm hy vọng của Bộ.',
    ability: 'Nếu có 1 HPH bị TTTT giết ban ngày, Kingsley có 50% cơ hội (tung đồng xu bởi GM) cứu sống người đó.',
    tacticalTip: 'Kích hoạt thế trận ứng cứu mỗi khi cảm nhận phe ác sắp ra đòn nhắm vào nhân vật mấu chốt.',
    flavorQuote: '“The Ministry has fallen. Scrimgeour is dead. They are coming.”',
    badge: 'shield',
    image: '/cards/kingsley.jpg'
  },
  BILL_WEASLEY: {
    id: 'BILL_WEASLEY',
    name: 'Bill Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phá Bùa Cổ Xưa · Curse Breaker',
    phaseType: 'PASSIVE',
    cardNumber: '№ 14/21',
    description: 'Chuyên gia phá bùa Gringotts, cưỡi Thestral chiến đấu bên cạnh người bạn đời.',
    ability: 'Nếu bị TTTT nhắm giết, chỉ chết khi Fleur cũng bị nhắm giết cùng lúc trong đêm đó.',
    tacticalTip: 'Tạo nên cặp đôi bất tử nếu phe ác không phát hiện ra cả hai người cùng lúc.',
    flavorQuote: '“It’d take more than a werewolf to stop Fleur loving me.”',
    badge: 'ring',
    image: '/cards/bill.jpg'
  },
  FLEUR_DELACOUR: {
    id: 'FLEUR_DELACOUR',
    name: 'Fleur Delacour',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Tình Yêu Veela · Beauxbatons Champion',
    phaseType: 'PASSIVE',
    cardNumber: '№ 15/21',
    description: 'Nữ quán quân tài hoa, vẻ đẹp kiêu kỳ gắn liền với sự thủy chung sắt son.',
    ability: 'Nếu bị TTTT nhắm giết, chỉ chết khi Bill cũng bị nhắm giết cùng lúc trong đêm đó.',
    tacticalTip: 'Cùng Bill phối hợp ngầm để hút đòn tấn công lãng phí từ Tử Thần Thực Tử.',
    flavorQuote: '“I am good-looking enough for both of us, I theenk!”',
    badge: 'ring',
    image: '/cards/fleur.jpg'
  },
  NYMPHADORA_TONKS: {
    id: 'NYMPHADORA_TONKS',
    name: 'Nymphadora Tonks',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phù Thủy Biến Hình · Metamorphmagus',
    phaseType: 'SPECIAL',
    cardNumber: '№ 16/21',
    description: 'Khả năng thay đổi dung mạo tùy ý, luôn mang lại bất ngờ cho chiến trường.',
    ability: 'Khi chết, có thể chọn biến thành 1 người khác (Kế thừa vai trò và năng lực của người đó).',
    tacticalTip: 'Khi ngã xuống, hãy kế thừa vai trò của người nắm giữ kỹ năng mạnh nhất đã chết.',
    flavorQuote: '“Don’t call me Nymphadora, Remus. It’s Tonks.”',
    badge: 'mask',
    image: '/cards/tonks.jpg'
  },
  POTTER_FAKE: {
    id: 'POTTER_FAKE',
    name: 'Bản Sao Harry',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Bảo Vệ · Polyjuice Decoy',
    phaseType: 'NIGHT',
    cardNumber: '№ 17/21',
    description: 'Uống thuốc Đa Quả Dịch mang khuôn mặt Harry để đánh lừa Chúa Tể Hắc Ám.',
    ability: 'Chỉ có quyền vote vào Ban Đêm. Không có kỹ năng kích hoạt ban ngày nhưng là lá chắn sinh tử của Hội.',
    tacticalTip: 'Đóng giả là Harry thật trong các cuộc tranh luận để dụ dỗ kẻ thù tiêu tốn ám sát vào bạn.',
    flavorQuote: '“We are all Harry tonight.”',
    badge: 'potion',
    image: '/cards/potter_fake.jpg'
  },

  // === TỬ THẦN THỰC TỬ (DEATH EATERS) — EMERALD & SILVER ===
  VOLDEMORT: {
    id: 'VOLDEMORT',
    name: 'Chúa Tể Voldemort',
    faction: 'DEATH_EATERS',
    title: 'Chúa Tể Hắc Ám · He-Who-Must-Not-Be-Named',
    phaseType: 'DAY',
    cardNumber: '№ 18/21',
    description: 'Kẻ thống trị nghệ thuật Hắc Ám, dẫn đầu cuộc truy kích bầu trời với bùa phép chết chóc.',
    ability: 'Biết mặt toàn bộ TTTT. Quyết định ám sát ban ngày. Nếu bị giết, Tử Thần Thực Tử thua ngay lập tức.',
    tacticalTip: 'Giữ kín thân phận tuyệt đối. Để Bellatrix và Malfoy làm bia đỡ đạn cho bạn trong các cuộc bỏ phiếu.',
    flavorQuote: '“There is no good and evil, there is only power, and those too weak to seek it.”',
    badge: 'dark_mark',
    image: '/cards/voldemort.jpg'
  },
  BELLATRIX_LESTRANGE: {
    id: 'BELLATRIX_LESTRANGE',
    name: 'Bellatrix Lestrange',
    faction: 'DEATH_EATERS',
    title: 'Nữ Tử Thần Cuồng Tín · Dark Lieutenant',
    phaseType: 'PASSIVE',
    cardNumber: '№ 19/21',
    description: 'Tay sai trung thành cuồng tín nhất, tàn bạo và sẵn sàng tử vì đạo vì Chúa Tể.',
    ability: 'Nếu Bellatrix bị treo cổ, ban ngày tiếp theo, Voldemort được quyền giết 2 người (Cơn thịnh nộ báo thù).',
    tacticalTip: 'Bạn là bẫy tử thần! Nếu bị dồn vào đường cùng, hãy để bị treo cổ để Voldemort quét sạch đối thủ.',
    flavorQuote: '“I killed Sirius Black! You coming to get me?”',
    badge: 'dagger',
    image: '/cards/bellatrix.jpg'
  },
  LUCIUS_MALFOY: {
    id: 'LUCIUS_MALFOY',
    name: 'Lucius Malfoy',
    faction: 'DEATH_EATERS',
    title: 'Quý Tộc Xảo Quyệt · Pureblood Patrician',
    phaseType: 'PASSIVE',
    cardNumber: '№ 20/21',
    description: 'Ngoại giao giảo hoạt, luôn toan tính để gia tộc Malfoy sống sót.',
    ability: 'Nếu Lucius bị treo cổ, ban ngày tiếp theo Voldemort sẽ bị khóa (Không được giết do mất trượng).',
    tacticalTip: 'Tuyệt đối không được để bị nghi ngờ hay treo cổ, vì điều đó làm tê liệt mũi nhọn của Voldemort.',
    flavorQuote: '“Let us hope Mr. Potter will always be around to save the day.”',
    badge: 'snake',
    image: '/cards/lucius.jpg'
  },
  PETER_PETTIGREW: {
    id: 'PETER_PETTIGREW',
    name: 'Peter Pettigrew',
    faction: 'DEATH_EATERS',
    title: 'Đuôi Trùn Phản Bội · Wormtail',
    phaseType: 'DAY',
    cardNumber: '№ 21/21',
    description: 'Kẻ chỉ điểm hèn hạ, mang hình hài chuột ẩn nấp moi móc thông tin của Hội.',
    ability: 'Ban ngày, có thể soi 1 người để biết họ có phải Hội Phượng Hoàng hay không.',
    tacticalTip: 'Dùng khả năng soi để loại trừ các bản sao Harry và chỉ điểm cho Voldemort tìm ra các mục tiêu cao cấp.',
    flavorQuote: '“He’s back! He’s returned, Lord Voldemort has risen!”',
    badge: 'rat',
    image: '/cards/pettigrew.jpg'
  },
  FENRIR_GREYBACK: {
    id: 'FENRIR_GREYBACK',
    name: 'Fenrir Greyback',
    faction: 'DEATH_EATERS',
    title: 'Ma Sói Đồ Tể · Lycanthrope Savage',
    phaseType: 'DAY',
    cardNumber: '№ 22/21',
    description: 'Hung thần của bóng đêm, thích cắn xé và biến đổi phù thủy thành sinh vật lang thang.',
    ability: 'Một lần trong game, có thể cắn 1 người. Người đó biến thành Ma Sói (Trung Lập) và mất toàn bộ kỹ năng HPH.',
    tacticalTip: 'Cắn một đồng minh mạnh của phe Phượng Hoàng như Dumbledore hoặc Moody để làm suy yếu lực lượng đối phương.',
    flavorQuote: '“I like to bite ’em young... makes ’em easier to train.”',
    badge: 'wolf',
    image: '/cards/greyback.jpg'
  }
};
