import { Role } from './types';

export const ROLES: Record<string, Role> = {
  // === HỘI PHƯỢNG HOÀNG (ORDER OF THE PHOENIX) — CRIMSON & GOLD ===
  HARRY_POTTER: {
    id: 'HARRY_POTTER',
    name: 'Harry Potter',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Kẻ Được Chọn · The Boy Who Lived',
    phaseType: 'PASSIVE',
    cardNumber: '№ 01/22',
    description: 'Trái tim của chiến dịch Bảy Potter và mục tiêu săn đuổi tối thượng của Voldemort.',
    ability: 'Bạn là mục tiêu săn lùng số 1 của Chúa Tể Voldemort. Đũa phép sở hữu Tia Lửa Vàng (Golden Flame Retaliation): Tự động thiêu rụi đòn chí mạng và cứu sống bạn khi bị tấn công trực diện lần đầu tiên (1 lần duy nhất trong toàn trận; không câm lặng Voldemort). Nếu bạn sống sót tới Hang Sóc (The Burrow - Chặng cuối) hoặc Hội tiêu diệt được Voldemort, Hội Phượng Hoàng THẮNG NGAY LẬP TỨC!',
    tacticalTip: 'Hãy ẩn mình cẩn trọng trên Mạng Floo, tận dụng các bản sao Potter Fake và đồng đội Bay Hộ Tống chắn đòn. Sống sót tới Hang Sóc là chìa khóa chiến thắng tối thượng!',
    flavorQuote: '“I don’t want anyone else to try to be a hero for me.”',
    badge: 'lightning',
    image: '/cards/harry.jpg'
  },
  RON_WEASLEY: {
    id: 'RON_WEASLEY',
    name: 'Ron Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Bạn Trung Thành · King Weasley',
    phaseType: 'PASSIVE',
    cardNumber: '№ 02/22',
    description: 'Dũng cảm, kiên định và sẵn sàng hy sinh thân mình vì tình bạn.',
    ability: 'Tấm khiên sinh mệnh của Harry. Nếu Harry Potter thật bị Tử Thần Thực Tử tấn công trực diện vào ban đêm (khi Tia Lửa Vàng đã cạn và không có người Bay Hộ Tống chắn đòn), Ron sẽ tự động dũng cảm lao ra đỡ đòn chí mạng chết thay cho Harry!',
    tacticalTip: 'Bạn là tấm khiên sinh mệnh tối hậu của Harry. Hãy cùng các bản sao phân tán sự chú ý của phe ác về phía mình, bảo vệ an toàn cho Harry thật!',
    flavorQuote: '“Don’t let it worry you. It’s me, I’m extremely famous.”',
    badge: 'shield',
    image: '/cards/ron.jpg'
  },
  HERMIONE_GRANGER: {
    id: 'HERMIONE_GRANGER',
    name: 'Hermione Granger',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phù Thủy Uyên Bác · Brightest Witch',
    phaseType: 'NIGHT',
    cardNumber: '№ 03/22',
    description: 'Trí tuệ sắc bén, lập kế hoạch chi tiết cho cuộc trốn chạy định mệnh.',
    ability: 'Mỗi ban Đêm, có thể thi triển bùa Soi Danh Tính để biết chính xác vai trò thật của 1 người chơi (không thể soi Harry Potter hay Chúa Tể Voldemort; Severus Snape có Bế Quan Bí Thuật sẽ hiển thị "Tâm Trí Bất Khả Xâm Phạm"). Giới hạn: Ở bàn ≤ 6 người, chỉ xuất hiện tối đa 1 trong 2: Hermione hoặc Arthur Weasley.',
    tacticalTip: 'Ưu tiên soi những người có phát ngôn bất thường hoặc dẫn dắt biểu quyết ban ngày để tìm ra Tử Thần Thực Tử. Cung cấp thông tin chuẩn xác cho Hội biểu quyết.',
    flavorQuote: '“Fear of a name only increases fear of the thing itself.”',
    badge: 'book',
    image: '/cards/hermione.jpg'
  },
  ALBUS_DUMBLEDORE: {
    id: 'ALBUS_DUMBLEDORE',
    name: 'Albus Dumbledore',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Hiệu Trưởng Vĩ Đại · Supreme Mugwump',
    phaseType: 'NIGHT',
    cardNumber: '№ 04/22',
    description: 'Phù thủy vĩ đại nhất mọi thời đại, bảo hộ linh hồn Hogwarts.',
    ability: 'Mỗi ban Đêm, chọn 1 người chơi để bảo vệ khỏi bị Tử Thần Thực Tử ám sát. Không được bảo vệ cùng 1 người 2 lượt liên tiếp.',
    tacticalTip: 'Dự đoán mục tiêu bị nhắm bắn tiếp theo. Đừng bảo vệ bản thân quá nhiều nếu đồng đội then chốt đang gặp hiểm nguy.',
    flavorQuote: '“Words are, in my not-so-humble opinion, our most inexhaustible source of magic.”',
    badge: 'phoenix',
    image: '/cards/dumbledore.jpg'
  },
  SEVERUS_SNAPE: {
    id: 'SEVERUS_SNAPE',
    name: 'Severus Snape',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Bậc Thầy Bế Quan Bí Thuật · Điệp Viên Hai Mang',
    phaseType: 'NIGHT',
    cardNumber: '№ 05/22',
    description: 'Bậc thầy Độc Dược và Bế Quan Bí Thuật, người điệp viên cô độc mang gánh nặng sinh tử của Hội Phượng Hoàng.',
    ability: 'Mỗi đêm, Snape có thể niệm Sectumsempra bọc lót cho 1 người chơi: Nếu người đó bị Tử Thần Thực Tử tấn công, bùa chém của Snape sẽ rạch nát đòn ám sát, cứu sống mục tiêu! Nhưng nếu người đó KHÔNG bị tấn công, bùa lạc sẽ cắt đứt tai / làm bị thương khiến mục tiêu bị phong ấn kỹ năng ở vòng kế tiếp. Ngoài ra, nhờ Bế Quan Bí Thuật, Snape hoàn toàn miễn nhiễm trước các bùa soi danh tính.',
    tacticalTip: 'Hãy phán đoán mục tiêu hiểm yếu mà phe Ác sắp ám sát để bọc lót cứu mạng! Tránh niệm bùa bừa bãi vào đồng đội vô tội nếu không muốn họ bị trúng bùa lạc mất tai và tê liệt kỹ năng!',
    flavorQuote: '“After all this time? Always.”',
    badge: 'potion',
    image: '/cards/snape.jpg'
  },
  REMUS_LUPIN: {
    id: 'REMUS_LUPIN',
    name: 'Remus Lupin',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Sói Hào Hiệp · Moony',
    phaseType: 'NIGHT',
    cardNumber: '№ 06/22',
    description: 'Chiến binh quả cảm của Hội, chuyên gia phòng chống nghệ thuật Hắc Ám.',
    ability: 'Sở hữu 1 lọ Thuốc Hồi Sinh độc dược quý giá (1 lần duy nhất trong toàn trận). Vào ban đêm, Lupin có thể âm thầm chọn 1 đồng đội đã ngã xuống (bị trục xuất ban ngày hoặc bị ám sát trong đêm) để hồi sinh. Hành động diễn ra hoàn toàn bí mật trong đêm (phe Tử Thần Thực Tử không biết trước), và mục tiêu sẽ chính thức sống lại vào rạng sáng hôm sau trong Báo Cáo Tuyệt Mật của Quản Trò Merlin. (Nếu Lupin bị giết cùng đêm, bùa hồi sinh bị ngắt).',
    tacticalTip: 'Dành bình thuốc hồi sinh cho các nhân vật chủ chốt như Harry Potter, Dumbledore, Hermione hoặc Thần Sáng khi họ ngã xuống để lật ngược thế cờ!',
    flavorQuote: '“It is the quality of one’s convictions that determines success, not the number of followers.”',
    badge: 'moon',
    image: '/cards/lupin.jpg'
  },
  ALASTOR_MOODY: {
    id: 'ALASTOR_MOODY',
    name: 'Alastor "Mắt Điên" Moody',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Thần Sáng Khét Tiếng · Constant Vigilance',
    phaseType: 'DAY',
    cardNumber: '№ 07/22',
    description: 'Chỉ huy chiến thuật của chiến dịch Bảy Potter, cảnh giác cao độ không khoan nhượng.',
    ability: 'Có 1 phát đạn Avada Kedavra vào Ban Ngày (lúc Biểu Quyết Bùa Tước Khí Giới), có thể lập tức bắn chết 1 người chơi. Tuy nhiên, nếu bắn nhầm thành viên Hội Phượng Hoàng, Moody sẽ tự vẫn vì ân hận.',
    tacticalTip: 'Chỉ bóp cò khi bạn có bằng chứng chắc chắn trên 90% kẻ đó là Tử Thần Thực Tử.',
    flavorQuote: '“Constant vigilance! Never let your guard down!”',
    badge: 'wand',
    image: '/cards/moody.jpg'
  },
  RUBEUS_HAGRID: {
    id: 'RUBEUS_HAGRID',
    name: 'Rubeus Hagrid',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Lai Khổng Lồ · Keeper of Keys',
    phaseType: 'NIGHT',
    cardNumber: '№ 08/22',
    description: 'Người lái chiếc mô tô bay đưa Harry xuyên qua làn mưa bùa chú tử thần.',
    ability: 'Mỗi ban đêm, Bác Hagrid có thể đưa 1 đồng đội lên chiếc mô-tô bay khổng lồ để hộ tống bảo vệ họ an toàn. Nếu mục tiêu bị tấn công ở chặng nguy hiểm, Hagrid sẽ lấy thân mình chắn đòn tử thủ. Thể lực khổng lồ phi thường giúp Hagrid kiên cường trên bầu trời, là chỗ dựa vững chắc cho phi đội.',
    tacticalTip: 'Dùng mô-tô bay hộ tống Harry Potter thật hoặc nhân vật chủ chốt của Hội trong những chặng bay cam go để bảo toàn sinh mạng cho toàn đội!',
    flavorQuote: '“What’s comin’ will come, an’ we’ll meet it when it does.”',
    badge: 'shield',
    image: '/cards/hagrid.jpg'
  },
  ARTHUR_WEASLEY: {
    id: 'ARTHUR_WEASLEY',
    name: 'Arthur Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Trụ Cột Nhà Weasley · Ministry Veteran',
    phaseType: 'NIGHT',
    cardNumber: '№ 09/22',
    description: 'Người cha tận tụy của gia đình Weasley, luôn theo dõi hoạt động của thế lực Hắc Ám tại Bộ.',
    ability: 'Mỗi ban Đêm, có thể chọn 1 người chơi để Soi Phe, kiểm tra xem người đó thuộc phe HỘI PHƯỢNG HOÀNG, TỬ THẦN THỰC TỬ hay TRUNG LẬP. Giới hạn: Ở bàn ≤ 6 người, chỉ xuất hiện tối đa 1 trong 2: Hermione hoặc Arthur Weasley.',
    tacticalTip: 'Tích cực soi phe vào ban đêm để phân loại người chơi khả nghi và cung cấp thông tin dẫn dắt phe Sáng biểu quyết ban ngày.',
    flavorQuote: '“Never trust anything that can think for itself if you can’t see where it keeps its brain.”',
    badge: 'phoenix',
    image: '/cards/arthur.jpg'
  },
  FRED_WEASLEY: {
    id: 'FRED_WEASLEY',
    name: 'Fred Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Anh Em Sinh Đôi · Weasley Twin',
    phaseType: 'NIGHT',
    cardNumber: '№ 10/22',
    description: 'Hài hước, táo bạo và không hề nao núng trước thế lực bóng tối. Đồng sáng lập tiệm Phù Thủy Quỷ Quái.',
    ability: 'Mỗi ban Đêm, có thể lén tặng 1 viên Kẹo Ngất Xỉu (Fainting Fancies) cho 1 người chơi còn sống. Nạn nhân ăn kẹo sẽ bị choáng váng và mất quyền biểu quyết (vote) ở vòng phán quyết ban ngày tiếp theo.',
    tacticalTip: 'Tặng kẹo cho kẻ bị tình nghi là Tử Thần Thực Tử cầm đầu hoặc kẻ hay dẫn dắt biểu quyết ban ngày để làm tê liệt sức mạnh của phe ác!',
    flavorQuote: '“Mischief managed! We solemnly swear that we are up to no good.”',
    badge: 'potion',
    image: '/cards/fred.jpg'
  },
  GEORGE_WEASLEY: {
    id: 'GEORGE_WEASLEY',
    name: 'George Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Anh Em Sinh Đôi · Saint-like',
    phaseType: 'NIGHT',
    cardNumber: '№ 11/22',
    description: 'Dù mất đi một bên tai trong trận không chiến, lòng dũng cảm vẫn vẹn nguyên. Đồng sáng lập tiệm Phù Thủy Quỷ Quái.',
    ability: 'Mỗi đêm, có thể tạo 1 Bột Khói Mù Peru và rải lên bầu trời. Toàn bộ Tử Thần Thực Tử bị SULK (mất quyền ám sát) trong đêm đó. **Lưu ý: Cần nghỉ 1 đêm giữa mỗi lần rải bột (cooldown 1 đêm) để cân bằng trò chơi.**',
    tacticalTip: 'Chờ thời điểm then chốt khi Dumbledore không thể bảo vệ hoặc khi phe Sáng đang nguy cấp để vô hiệu hóa hoàn toàn đợt tấn công của phe ác!',
    flavorQuote: '”You see, I\'m holy, Fred. Geddit? Saint-like.”',
    badge: 'potion',
    image: '/cards/george.jpg'
  },
  MUNDUNGUS_FLETCHER: {
    id: 'MUNDUNGUS_FLETCHER',
    name: 'Mundungus Fletcher',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Kẻ Hèn Nhát · Scoundrel of the Order',
    phaseType: 'SPECIAL',
    cardNumber: '№ 12/22',
    description: 'Tay buôn lậu chợ đen, luôn tìm cách luồn lách bảo toàn mạng sống.',
    ability: 'Khi bị Tử Thần Thực Tử tấn công chí mạng vào ban đêm, bản năng sinh tồn trỗi dậy kích hoạt cơ chế khẩn cấp: Mundungus được tự tay bấm chọn 1 người chơi còn sống bất kỳ trên bàn để Độn Thổ lôi họ ra chết thay mình! (1 lần duy nhất trong toàn trận).',
    tacticalTip: 'Nếu bị nhắm bắn, hãy nhanh tay chọn kẻ mà bạn nghi ngờ nhất là phe ác để thế mạng đổi mạng!',
    flavorQuote: '“I never volunteered for this! There was hundreds of ’em!”',
    badge: 'mask',
    image: '/cards/mundungus.jpg'
  },
  KINGSLEY_SHACKLEBOLT: {
    id: 'KINGSLEY_SHACKLEBOLT',
    name: 'Kingsley Shacklebolt',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Thần Sáng Hoàng Gia · Auror Commander',
    phaseType: 'NIGHT',
    cardNumber: '№ 13/22',
    description: 'Thần Sáng điềm tĩnh, chỉ huy đội cận vệ và là niềm hy vọng của Bộ.',
    ability: 'Nếu có 1 thành viên Hội Phượng Hoàng bị Tử Thần Thực Tử hạ sát trong đêm, Kingsley sẽ CỨU SỐNG người đó an toàn (100% thành công)! Ngoài ra, Kingsley hoàn toàn miễn nhiễm trước mọi loại bùa Câm Lặng (Silencing).',
    tacticalTip: 'Luôn kích hoạt thế trận ứng cứu ban đêm để giữ mạng cho các thành viên nòng cốt. Với khả năng miễn nhiễm câm lặng, Kingsley là chốt chặn phòng ngự đáng tin cậy nhất của Hội!',
    flavorQuote: '”The Ministry has fallen. Scrimgeour is dead. They are coming.”',
    badge: 'shield',
    image: '/cards/kingsley.jpg'
  },
  BILL_WEASLEY: {
    id: 'BILL_WEASLEY',
    name: 'Bill Weasley',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phá Bùa Cổ Xưa · Curse Breaker',
    phaseType: 'NIGHT',
    cardNumber: '№ 14/22',
    description: 'Chuyên gia phá bùa Gringotts, cưỡi Thestral chiến đấu bên cạnh người bạn đời. Kinh nghiệm chiến đấu với bùa chú cổ nguy hiểm.',
    ability: 'Mỗi ban Đêm, có thể dùng chuyên môn Phá Bùa (Curse Breaker) chọn 1 người chơi đang bị phong ấn kỹ năng (do bùa lạc Sectumsempra của Snape hoặc các bùa câm lặng khác) để giải thoát và khôi phục năng lực sử dụng kỹ năng cho họ.',
    tacticalTip: 'Theo dõi sát sao tình hình ban đêm để kịp thời giải bùa cho những đồng minh chủ chốt như Dumbledore, Hermione hay Snape nếu họ không may bị dính bùa câm lặng.',
    flavorQuote: '”It would take more than a werewolf to stop Fleur loving me.”',
    badge: 'ring',
    image: '/cards/bill.jpg'
  },
  FLEUR_DELACOUR: {
    id: 'FLEUR_DELACOUR',
    name: 'Fleur Delacour',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Tình Yêu Veela · Beauxbatons Champion',
    phaseType: 'NIGHT',
    cardNumber: '№ 15/22',
    description: 'Nữ quán quân tài hoa từ Beauxbatons, vẻ đẹp kiêu kỳ gắn liền với sự thủy chung sắt son. Lưỡi kiếm bạc của mình là vũ khí lợi hại.',
    ability: 'Mỗi ban Đêm, Fleur có thể dùng Lưỡi Kiếm Gryffindor để chém 1 người chơi. Nếu mục tiêu thuộc phe Tử Thần Thực Tử, kẻ đó bị LOẠI KHỎI TRÒ CHƠI NGAY LẬP TỨC (không cần qua biểu quyết). Tuy nhiên, nếu chém nhầm đồng minh Hội Phượng Hoàng, Fleur sẽ tự vẫn vì tội lỗi!',
    tacticalTip: 'Vũ khí sát thương cực mạnh nhưng rủi ro cao. Hãy kết hợp thông tin soi phe từ Hermione hoặc Arthur để chắc chắn trước khi xuất kiếm!',
    flavorQuote: '”I am good-looking enough for both of us, I theenk!”',
    badge: 'ring',
    image: '/cards/fleur.jpg'
  },
  NYMPHADORA_TONKS: {
    id: 'NYMPHADORA_TONKS',
    name: 'Nymphadora Tonks',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Phù Thủy Biến Hình · Metamorphmagus',
    phaseType: 'SPECIAL',
    cardNumber: '№ 16/22',
    description: 'Khả năng thay đổi dung mạo tùy ý, luôn mang lại bất ngờ cho chiến trường.',
    ability: 'Khi tử trận, Tonks có thể kích hoạt khả năng biến hình để chọn kế thừa vai trò và toàn bộ năng lực ma thuật của một người chơi đã khuất trên bàn.',
    tacticalTip: 'Khi ngã xuống, hãy quan sát mộ địa và lựa chọn kế thừa vai trò của nhân vật có năng lực mạnh nhất (như Dumbledore, Hermione, Moody, Kingsley) để tiếp tục chiến đấu cho Hội.',
    flavorQuote: '“Don’t call me Nymphadora, Remus. It’s Tonks.”',
    badge: 'mask',
    image: '/cards/tonks.jpg'
  },
  POTTER_FAKE: {
    id: 'POTTER_FAKE',
    name: 'Bản Sao Harry',
    faction: 'ORDER_OF_PHOENIX',
    title: 'Người Bảo Vệ · Polyjuice Decoy',
    phaseType: 'SPECIAL',
    cardNumber: '№ 17/22',
    description: 'Uống thuốc Đa Quả Dịch mang khuôn mặt Harry để đánh lừa Chúa Tể Hắc Ám.',
    ability: 'Mang ngoại hình Harry Potter để phân tán sự chú ý của kẻ thù. Có quyền biểu quyết ban ngày và Bay Hộ Tống ban đêm. Ngoài ra, 1 lần duy nhất trong toàn trận, có thể tự nguyện Reveal thân phận là Potter Fake và niệm bùa phong ấn (SILENCED) lên 1 kẻ thuộc phe Tử Thần Thực Tử, khiến kẻ đó bị tước toàn bộ kỹ năng ở vòng tiếp theo!',
    tacticalTip: 'Đóng giả làm Harry thật trong các cuộc tranh luận để dụ phe ác dồn sát thương vào bạn. Dùng Silenced Ultimate vào kẻ ác nguy hiểm nhất khi cần vô hiệu hóa chúng!',
    flavorQuote: '”We are all Harry tonight.”',
    badge: 'potion',
    image: '/cards/potter_fake.jpg'
  },

  // === TỬ THẦN THỰC TỬ (DEATH EATERS) — EMERALD & SILVER ===
  VOLDEMORT: {
    id: 'VOLDEMORT',
    name: 'Chúa Tể Voldemort',
    faction: 'DEATH_EATERS',
    title: 'Chúa Tể Hắc Ám · He-Who-Must-Not-Be-Named',
    phaseType: 'NIGHT',
    cardNumber: '№ 18/22',
    description: 'Kẻ thống trị nghệ thuật Hắc Ám, dẫn đầu cuộc truy kích bầu trời với bùa phép chết chóc.',
    ability: 'Biết mặt toàn bộ Tử Thần Thực Tử và nắm quyền quyết định tối cao về mục tiêu ám sát trong đêm (hoặc ra lệnh Án Binh Bất Động). Nếu Chúa Tể Voldemort bị tiêu diệt (bị biểu quyết ban ngày hoặc bị trúng đạn Moody/kiếm Fleur), phe Tử Thần Thực Tử THUA NGAY LẬP TỨC!',
    tacticalTip: 'Giữ kín thân phận tuyệt đối. Để Bellatrix và Lucius làm bia đỡ đạn trong các cuộc bỏ phiếu. Có thể chọn Án Binh để thăm dò hoặc tránh kích hoạt bẫy phản công!',
    flavorQuote: '“There is no good and evil, there is only power, and those too weak to seek it.”',
    badge: 'dark_mark',
    image: '/cards/voldemort.jpg'
  },
  BELLATRIX_LESTRANGE: {
    id: 'BELLATRIX_LESTRANGE',
    name: 'Bellatrix Lestrange',
    faction: 'DEATH_EATERS',
    title: 'Nữ Tử Thần Cuồng Tín · Dark Lieutenant',
    phaseType: 'PASSIVE',
    cardNumber: '№ 19/22',
    description: 'Tay sai trung thành cuồng tín nhất, tàn bạo và sẵn sàng tử vì đạo vì Chúa Tể.',
    ability: 'Nếu Bellatrix bị xử tử bằng biểu quyết Tước Đũa ban ngày, cơn thịnh nộ báo thù bùng nổ giúp Chúa Tể Voldemort được quyền ám sát liên tiếp 2 người (Double Kill) trong đêm tiếp theo!',
    tacticalTip: 'Bạn là chiếc bẫy tử thần! Nếu bị dồn vào đường cùng, hãy khiêu khích để bị treo cổ, tạo cơ hội cho Voldemort quét sạch phe Sáng!',
    flavorQuote: '“I killed Sirius Black! You coming to get me?”',
    badge: 'dagger',
    image: '/cards/bellatrix.jpg'
  },
  LUCIUS_MALFOY: {
    id: 'LUCIUS_MALFOY',
    name: 'Lucius Malfoy',
    faction: 'DEATH_EATERS',
    title: 'Quý Tộc Xảo Quyệt · Pureblood Patrician',
    phaseType: 'NIGHT',
    cardNumber: '№ 20/22',
    description: 'Ngoại giao giảo hoạt, luôn toan tính để gia tộc Malfoy sống sót.',
    ability: 'Mỗi ban Đêm, Lucius có thể chọn 1 người chơi để soi và biết chính xác vai trò cụ thể của người đó (Spy). Ngoài ra, nếu Lucius bị treo cổ ban ngày, mối liên hệ gia tộc bị đứt gãy khiến Voldemort bị KHÓA (không được phép ám sát) ở đêm tiếp theo.',
    tacticalTip: 'Dùng khả năng soi đêm để tìm ra ai là Harry thật hoặc các nhân vật then chốt. Cẩn trọng khi biểu quyết ban ngày để tránh làm Voldemort bị khóa đòn ám sát!',
    flavorQuote: '”Let us hope Mr. Potter will always be around to save the day.”',
    badge: 'snake',
    image: '/cards/lucius.jpg'
  },
  PETER_PETTIGREW: {
    id: 'PETER_PETTIGREW',
    name: 'Peter Pettigrew',
    faction: 'DEATH_EATERS',
    title: 'Kẻ Phản Bội · Đuôi Trùn (Wormtail)',
    phaseType: 'NIGHT',
    cardNumber: '№ 21/22',
    description: 'Kẻ phản bội hèn hạ hóa thú thành chuột Scabbers, bầy tôi nợ mạng Harry Potter nhưng mang Bàn Tay Bạc của Chúa Tể Hắc Ám.',
    ability: 'Mỗi đêm trước khi giết, Pettigrew có thể chọn 1 người phe HPH để Đánh Hơi: Nhờ 12 năm sống ở Nhà Hang Sóc, nếu soi trúng Ron Weasley hoặc Harry Potter thật, hắn sẽ nhận diện ĐÍCH DANH người đó! Nếu trúng người khác, hắn biết họ là Đặc Biệt hay Bản Sao. Tuy nhiên, do mang Món Nợ Mạng (Life Debt) với Harry, Pettigrew KHÔNG THỂ trực tiếp bỏ phiếu ám sát Harry Potter thật. Ngoài ra, lần đầu tiên bị trục xuất ban ngày, hắn sẽ tự cắt ngón tay hóa chuột đào tẩu thoát chết!',
    tacticalTip: 'Hãy dùng khứu giác loài chuột để đánh hơi tìm ra đích danh Ron hoặc Harry Potter thật cho Voldemort. Nhưng nhớ rằng: bàn tay bạc của bạn sẽ bị tê liệt trước Harry do Món Nợ Máu, hãy để Voldemort hoặc đồng minh kết liễu Harry!',
    flavorQuote: '“You owe me, Wormtail! Your life belongs to me!”',
    badge: 'rat',
    image: '/cards/pettigrew.jpg'
  },
  FENRIR_GREYBACK: {
    id: 'FENRIR_GREYBACK',
    name: 'Fenrir Greyback',
    faction: 'DEATH_EATERS',
    title: 'Ma Sói Đồ Tể · Lycanthrope Savage',
    phaseType: 'NIGHT',
    cardNumber: '№ 22/22',
    description: 'Hung thần của bóng đêm, thích cắn xé và biến đổi phù thủy thành sinh vật lang thang.',
    ability: 'Một lần duy nhất trong toàn trận vào ban đêm, Fenrir có thể cắn 1 người chơi (không thể cắn Harry Potter hay đồng minh Tử Thần Thực Tử). Nạn nhân bị cắn sẽ bị CHUYỂN SANG PHE TỬ THẦN THỰC TỬ, trở thành đồng minh của phe Ác nhưng vẫn giữ nguyên kỹ năng cũ!',
    tacticalTip: 'Cắn những nhân vật có kỹ năng mạnh như Dumbledore, Hermione, hoặc Kingsley để biến họ thành đồng minh trung thành phục vụ cho phe Tử Thần Thực Tử!',
    flavorQuote: '“I like to bite \'em young... makes \'em easier to train.”',
    badge: 'wolf',
    image: '/cards/greyback.jpg'
  }
};
